### ISSUE TITLE
API suggestion: soup.all("div") and soup.first("div")

### ISSUE THREAD

**Issue by simonw** [maxhumber/gazpacho#33]
The default auto behavior of `.find()` doesn't work for me, because it means I can't trust my code not to start throwing errors if the page I am scraping adds another matching element, or drops the number of elements down to one (triggering a change in return type).

I know I can do this:

```python
div = soup.find("div", mode="first")
# Or this:
divs = soup.find("div", mode="all")
```

But having function parameters that change the return type is still a bit weird - not great for code hinting and suchlike.

Changing how `.find()` works would be a backwards incompatible change, which isn't good now that you're past the `1.0` release. I suggest adding two new methods instead:

```python
div = soup.first("div") # Returns a single element
# Or:
divs = soup.all("div") # Returns a list of elements
```
This would be consistent with your existing API design (promoting the mode arguments to first class method names) and could be implemented without breaking existing code.

**Comment by maxhumber** [comment]
Thanks for the suggestion, @simonw 

There's definitely merits to this approach! Ultimately, however, I decided against this about a year ago (#3).

My logic? `gazpacho` should be easy. It should be the best for prototyping (in a Jupyter environment). Because, when you're just figuring out how to web scrape a page, you just want to see what's on it...

Then, when you've figured the page out, you can manually guarantee the returns by setting `mode='all'` or `mode='first'` .

Also, for a laugh, go count up how many different ways bs4 can find something (it's more than 27!).

**Comment by simonw** [comment]
I totally understand your desire to keep the API as light as possible, but in this particular case I would counter that this doesn't make gazpacho easier to use, it makes it harder!

Every time I've worked with a library that varies its return type in unexpected ways it has surprised me and lead to bugs. When I was reading your dev.to article this jumped straight out at me as a pattern I've been burned by in the past.

**Comment by sorasful** [comment]
I second the use of .first or .all but I also understand the actual choice. But maybe use enums or something instead of plain strings to help ? Or a boolean ?

**Comment by pauliyobo** [comment]
In this case, I believe using .first() and .all() would make the  whole API easier, and would not necessarily clutter it.
I suppose they could initially just be  aliases that call to .find() with the appropriate mode.
After all explicit is better than implicit :) .

**Comment by maxhumber** [comment]
I really appreciate the feedback, and I hear you!, but let me offer an analogy: 

You know how to you have to [try three times to plug in a usb](https://images.techhive.com/images/article/2015/11/only-two-ways-lsuyd1-100625531-orig.jpg)? I think adding `first` and `all` on top of `find` would be like asking users to try three times to scrape something on a page.

If this package were doing anything other than web scraping I would agree, there should be different methods that enforce different return types. But web scraping is messy! It's iterative! You never know what you're going to get!

By having, and keeping, the returns from `find` automagical it makes interacting with the package like [plugging in one of these cables](https://assets.aten.com/product/image/2l-2505.cables.vga-cables.rear.jpg) (instead of a usb). It'll alwasy plug in the first time you plug it in, and then, when you know it, works you can screw it in (enforce types).

I hope that makes sense?

I created gazpacho because I was confused by the `bs4` docs. There was way too much shit to look through! I guess that's because `bs4` is totally comprehensive tool. Its for 100% of your web scraping needs. But gazpacho is a hammer. It's for 95% of your scraping problems. It doesn't want to be a hammer and chainsaw and a usb cable.

**Comment by simonw** [comment]
Another way you could cover this would be to add the `soup.select()` method from #9 and have that always return a list.

That way people like me who don't like the way `.find()` works could use `.select()` instead - a neat thing about CSS selectors is that the selector for a tag is just the name of the tag, so `.select("div")` would work as an alternative for `.find("div", mode="all")`.
